### ISSUE TITLE
Video Demo Request

### ISSUE THREAD

**Issue by NicoHinderling** [harshabakku/royalty-respecters-rewarder#1]
Hi @harshabakku ! Would it be possible for you to add a video demo to your README?

**Comment by harshabakku** [comment]
Thanks @NicoHinderling  I have added the below demo link in the end in the README.md file.  


https://www.youtube.com/watch?v=uCZTvtm1200

ps: I had already added the same video demo link when I was submitting my project on gitcoin before deadline.
